#Creating a Kubernetes Deployment manifest to deploy your Dockerized web service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-container
        image: nawdocker/python:3.9-slim-21  # Replace with your Docker image name
        ports:
        - containerPort: 80
